services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - my-network
    depends_on:
      - wordpress
    container_name: nginx
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/conf.d/:ro # read only, bonne pratique
      - wordpress_v:/var/www/html
    ports:
      - "443:443" # mapping des ports,  host:container
    privileged: true

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    container_name: wordpress
    volumes:
      - wordpress_v:/var/www/html
    env_file:
      - .env
    networks:
      - my-network

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - db_v:/var/lib/mysql
    env_file:
      - .env
    restart: always
    networks:
      - my-network

volumes:
  db_v:
    driver: local
    name: db_v
    driver_opts: # only if mounted volume
      device: /home/jikho/data/mariadb
      # TODO device: /home/jdefayes/data/mariadb
      type: none # none a volume handled by Docker, simple link to a local repo
      o: bind
  wordpress_v:
    driver: local
    name: wordpress_v
    driver_opts:
      device: /home/jikho/data/wordpress
      # TODO device: /home/jdefayes/data/wordpress
      type: none
      o: bind

networks:
  my-network:
    driver: bridge