services:
  nginx: # DONE
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    container_name: nginx
    volumes:
      #- ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - wordpress_v:/var/www/html
    ports:
      - "80:80"
    networks:
      - my-network

  wordpress:
    image: wordpress:php8.0-fpm
    depends_on:
      - mariadb
    container_name: wordpress
    expose:
      - 9000
    volumes:
      - wordpress_v:/var/www/html
      - /home/jikho/Documents/juju_maj/srcs/requirements/wordpress/tools/wp-config.php:/var/www/html/wp-config.php
    env_file:
      - .env
    networks:
      - my-network

  mariadb: # WORKING ON
    #image: mariadb:11.5.2
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - db_v:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - my-network

volumes:
  db_v:
    driver: local
    name: db_v
    driver_opts: # only if mounted volume
      device: /home/jikho/data/mariadb/
      type: none # none a volume handled by Docker, simple link to a local repo
      o: bind
  wordpress_v:
    driver: local
    name: wordpress_v
    driver_opts:
      device: /home/jikho/data/wordpress/
      type: none
      o: bind

networks:
  my-network:
    driver: bridge