services:
  nginx:
    #image: nginx:latest
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - my-network
    depends_on:
      - wordpress
    container_name: nginx
    volumes:
      - wordpress_v:/var/www/html
    ports:
      - "8080:80" # mapping ports (mettre 443 nginx) host:container
    privileged: true

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    #image: wordpress:php8.0-fpm
    depends_on:
      - mariadb
    container_name: wordpress
    expose:
      - 9001
    volumes:
      - wordpress_v:/var/www/html
    env_file:
      - .env
    networks:
      - my-network

  mariadb: # WORKING ON
   # image: mariadb:11.5.2
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    ports:
      - "3307:3306" # redirection de ports, port_host:port_container
    volumes:
      - db_v:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    # env_file:
    #   - .env
    restart: always
    networks:
      - my-network

volumes:
  db_v:
    driver: local
    name: db_v
    driver_opts: # only if mounted volume
      device: ./data/mariadb/
      type: none # none a volume handled by Docker, simple link to a local repo
      o: bind
  wordpress_v:
    driver: local
    name: wordpress_v
    driver_opts:
      device: ./data/wordpress/
      type: none
      o: bind

networks:
  my-network:
    driver: bridge